// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timeframe } from "./Timeframe";

export type GetCandlesQuery = { exchange: string, symbol: string, timeframe: Timeframe, start?: number, end?: number, };
