// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timeframe } from "./Timeframe";
import type { Trade } from "./Trade";

export type BacktestResult = { exchange: string, symbol: string, timeframe: Timeframe, candles_processed: number, final_balance: string, final_position: string, trades: Array<Trade>, };
