// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timeframe } from "./Timeframe";

export type CreateFetchCandlesTaskRequest = { symbol: string, exchange: string, timeframe: Timeframe, };
