// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FetchCandlesResult } from "./FetchCandlesResult";
import type { FetchCandlesStatus } from "./FetchCandlesStatus";
import type { Timeframe } from "./Timeframe";

export type FetchCandlesTask = { id: string, status: FetchCandlesStatus, progress: number, symbol: string, exchange: string, timeframe: Timeframe, result?: FetchCandlesResult, error_message?: string, created_at: number, started_at?: number, completed_at?: number, updated_at: number, };
